api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    enable_swagger: true
    enable_swagger_ui: true
    enable_re_doc: true
    enable_entrypoint: true
    enable_docs: true
    title: CUIT's
    version: 1.0
    show_webby: false
